// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/anisbouzahar/portfolio-api/internal/app/api/v1"
	"github.com/anisbouzahar/portfolio-api/internal/app/database"
	user3 "github.com/anisbouzahar/portfolio-api/internal/app/handlers/user"
	"github.com/anisbouzahar/portfolio-api/internal/app/http"
	"github.com/anisbouzahar/portfolio-api/internal/app/repository/user"
	user2 "github.com/anisbouzahar/portfolio-api/internal/app/services/user"
	"github.com/anisbouzahar/portfolio-api/pkg"
	"github.com/go-chi/chi/v5"
)

// Injectors from wire.go:

func InitializeServer() (*http.Server, func(), error) {
	logger, cleanup := pkg.NewLogger()
	mux := chi.NewRouter()
	mongoDb, cleanup2 := database.NewMongoDb()
	repository := user.NewUserRepository(mongoDb)
	service := user2.NewUserService(repository)
	handler := user3.NewHandler(service)
	api := v1.NewAPI(logger, mux, handler)
	server := http.NewServer(api)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
